export const ACTION_SET_SEARCH = 'ACTION_SET_SEARCH';

export const ACTION_ADD_STUDENT_DRAFT = 'ACTION_ADD_STUDENT_DRAFT';
export const ACTION_HIDE_ADD_STUDENT_MODEL = 'ACTION_HIDE_ADD_STUDENT_MODEL';

export const ACTION_GET_STUDENTS = 'ACTION_GET_STUDENTS';

export const ACTION_ADD_NEW_DRAFT_STUDENT = 'ACTION_ADD_NEW_DRAFT_STUDENT';
export const ACTION_POST_STUDENT = 'ACTION_POST_STUDENT';
export const ACTION_PUT_STUDENT = 'ACTION_PUT_STUDENT';

export const ACTION_GET_FAMILY = 'ACTION_GET_FAMILY';
export const ACTION_ADD_FAMILY_DRAFT = 'ACTION_ADD_FAMILY_DRAFT';

export const ACTION_SELECT_STUDENT = 'ACTION_SELECT_STUDENT';
export const ACTION_ADD_STUDENT = 'ACTION_ADD_STUDENT';
export const ACTION_SET_STUDENT_DETAIL = 'ACTION_SET_STUDENT_DETAIL';
