export const ACTION_SET_SEARCH = 'ACTION_SET_SEARCH';

export const ACTION_ADD_STUDENT = 'ACTION_ADD_STUDENT';
export const ACTION_ADD_STUDENT_FAMILY = 'ACTION_ADD_STUDENT_FAMILY';

export const ACTION_REVIEW_STUDENT = 'ACTION_REVIEW_STUDENT';
