export const ACTION_SET_SEARCH = 'ACTION_SET_SEARCH';

export const ACTION_SHOW_STUDENT_MODEL = 'ACTION_SHOW_STUDENT_MODEL';

export const ACTION_GET_STUDENTS = 'ACTION_GET_STUDENTS';

export const ACTION_ADD_STUDENTS = 'ACTION_ADD_STUDENTS';
export const ACTION_ADD_STUDENT_FAMILY = 'ACTION_ADD_STUDENT_FAMILY';

export const ACTION_REVIEW_STUDENT = 'ACTION_REVIEW_STUDENT';
